config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/flats'
  get 'dashboard/bookings'

  resources :flats do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create, :edit, :update] do
      member do
        patch '/accept', to: "bookings#accept"
        patch '/decline', to: "bookings#decline"
      end
    end
  end

  resources :users, only: [:edit, :update]

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def flats
    @flats = current_user.flats
  end

  def bookings
    @bookings = current_user.bookings
  end
end

app/views/dashboard/bookings.html.erb
<div class="booking-banner" id="banner-for-my-bookings" style="background-image: linear-gradient(to right, rgba(118, 184, 82,0.3) 10%, rgba(141, 194, 111,0.3) 70%), url(<%= image_path('my-booking.jpg') %>);">
  <div class="sign-in-flex">
    <div class="my-booking">My Bookings</div>

    </div>
</div>

<% @bookings.each do |booking| %>
<div class="container">

    <div class="tabs">
        <a href="<%= flat_path(booking.flat) %>" class="tab active"><%= booking.flat.name %></a>
        <%= link_to 'Edit', edit_flat_booking_path(booking.flat, booking), class: " green-button tabs-btn" %>
        <%= link_to 'Accept', accept_flat_booking_path(booking.flat, booking), method: :patch, class: " green-button tabs-btn" %>
        <%= link_to 'Decline', decline_flat_booking_path(booking.flat, booking), method: :patch, class: " green-button tabs-btn" %>
    </div>

    <ul class="inbox">
        <li class="message">
            <img src="<%= booking.flat.photo %>" class="flat-picture">
            <div class="message-name">
                <h3><%= booking.flat.user.firstname %> <%= booking.flat.user.lastname %></h3>
                <p>From: <%= booking.checkin %> <br> To: <%= booking.checkout %></p>
                <p><%= booking.guests %> persons</p>
            </div>
            <div class="message-body">
            <p>
                <strong><%= booking.flat.city %></strong>
            </p>
            <p>
                <%= booking.flat.description %>
            </p>
            <p>
                Free cancelation
            </p>
            </div>

        <div class="message-status">
            <p><%= booking.status %></p>
            <p class="price">€<%= booking.flat.price %></p>
        </div>

        </li>
    </ul>
    </div>
    <% end %>
    <hr>

app/views/dashboard/flats.html.erb
<div class="banner-main index-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 10%, rgba(0,36,61,0.3) 70%), url(<%= image_path('my-flats.jpg') %>);">
  <h1 class="title">Here you can see all flats that you currently renting out.</h1>
</div>
<div class="container">
  <div class="row">
    <% flat_user = @flats.each do |flat| %>
  <div class="col-xs-12 col-sm-4">
    <div class="card-detail-container">
      <%= link_to flat_path(flat) do %>
      <%= cl_image_tag flat.photo, class: "small-in-banner-flats"  %>
      <% end %>
      <div class="cards-description">
        <p class="paragraph-style"> Private room </p>
        <p class="paragraph-style" id="button"> <%= link_to flat.name, flat_path(flat) %> </p>
        <p class="paragraph-style" id="city"> <%= flat.city %> </p>
        <p class="other-details"> Capacity: <%= flat.capacity %> people </p>
        <p class="other-details"> <%= flat.price %>€ - free cancelation </p>
        <% if flat.rating == nil %>
          <span>No reviews</span>
        <% else %>
          <span class="rating"><% flat.rating.times do %>☆<% end %></span>
        <% end %>
      </div>
    </div>
  </div>
    <% end %>
</div>
</div>
<hr>