config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/flats'
  get 'dashboard/bookings'

  resources :flats do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create, :edit, :update] do
      member do
        patch '/accept', to: "bookings#accept"
        patch '/decline', to: "bookings#decline"
      end
    end
  end

  resources :users, only: [:edit, :update]

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :price, presence: true
  validates :photo, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :capacity, presence: true

  include PgSearch
  pg_search_scope :search_by_content,
    against: [ :name, :description, :address, :city ],
    using: {
      tsearch: { prefix: true }
    }

    # def reviews
    #   Review.where(flat_id: self.id)
    # end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  
  def index
    # @flats = policy_scope(Flat)

    if params[:query].present?
      @flats = Flat.search_by_content(params[:query])

      @markers = @flats.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
          # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
        }
      end
    else
      @flats = Flat.where.not(latitude: nil, longitude: nil)
      # @flats = Flat.all
      
      @markers = @flats.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
          # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
        }
      end
    end
  end

  def show
    authorize @flat
    @review = Review.new
  end

  def edit
    authorize @flat
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def update
    authorize @flat
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit
    end
  end

  def destroy
    authorize @flat
    @flat.destroy

    redirect_to flats_path
  end

  private 
  
  def flat_params
    params.require(:flat).permit(:name, :description, :photo, :price, :address, :city, :capacity) 
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/views/flats/_form.html.erb
<div class="sign-in-banner" id="banner-for-new" style="background-image: linear-gradient(to right, rgba(118, 184, 82,0.3) 10%, rgba(141, 194, 111,0.3) 70%), url(<%= image_path('update.jpg') %>);">
  <div class="sign-in-flex">
    <div class="new-form sign-in">
      <% if @flat.name.nil? %>
        <div class="sign-in-h2">Add a flat</div>
      <% else %>
        <div class="sign-in-h2">Update your flat</div>
      <% end %>
        <%= simple_form_for [@flat] do |f| %>
            <%= f.input :name, input_html: {class: "input-from-new"} %>
            <%= f.input :description, input_html: {class: "input-from-new"} %>
            <%= f.input :price, input_html: {class: "input-from-new"} %>
            <%= f.input :address, input_html: {class: "input-from-new", id: "flat_address"} %>
            <%= f.input :city, input_html: {class: "input-from-new"} %>
            <%= f.input :capacity, input_html: {class: "input-from-new"} %>
            <%= f.input :photo, input_html: {class: "input-from-new"} %>
            <div class="button-mask">Upload Photo</div>
            <%= f.input :photo_cache, as: :hidden, input_html: {class: "import-button"} %>
            <%= f.submit "save", class: "green-button" %>
        <% end %>
        <%= link_to 'Back', flats_path %>
    </div>
  </div>
</div>

app/views/flats/_review-form.html.erb
<div class="sign-in-flex">
  <div class="new-form-review sign-in">
    <%= simple_form_for [@flat, @review] do |f| %>
      <%= f.input :content, input_html: {class: "input-from-new-review"} %>
      <%= f.submit "add a review", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/flats/edit.html.erb
<%= render "form" %>

app/views/flats/index.html.erb
<div class="banner-main index-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 10%, rgba(0,36,61,0.3) 70%), url(<%= image_path('index-pic.jpg') %>);">
  <h1 class="title">Select the flat that better suites your needs from our great community.</h1>
</div>
<div class="container">
  <div class="row">
    <% flat_user = @flats.each do |flat| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card-detail-container">
        <%= link_to flat_path(flat) do %>
        <%= cl_image_tag flat.photo, class: "small-in-banner-flats"  %>
        <% end %>
          <div class="cards-description">
            <p class="paragraph-style"> Private room </p>
            <p class="paragraph-style" id="button"> <%= link_to flat.name, flat_path(flat) %> </p>
            <p class="paragraph-style" id="city"> <%= flat.city %> </p>
            <p class="other-details"> Capacity: <%= flat.capacity %> people </p>
            <p class="other-details"> <%= flat.price %>€ - free cancelation </p>
            <% if flat.rating == nil %>
              <span>No reviews</span>
            <% else %>
              <span class="rating"><% flat.rating.times do %>☆<% end %></span>
            <% end %>
        </div>
      </div>
    </div>
   <% end %>
  </div>
</div>
<div
id="map"
style="width: 100%;
height: 100vh;"
data-markers="<%= @markers.to_json %>"
></div>

app/views/flats/new.html.erb
<%= render "form" %>

app/views/flats/show.html.erb
<div class="sign-in-banner-flats" style="background-image: linear-gradient(to right, rgba(118, 184, 82,0.3) 10%, rgba(141, 194, 111,0.3) 70%), url('<%= cl_image_path @flat.photo, input_html: {class: "flat-picture"}  %>');">

  <div class="sign-in-flex-show">
    <div class="flat-description">
      <p class="sign-in-h1"> <%= @flat.name %> </p>
      <p class="description-title"><%= @flat.description %></p>
      <p>Owner: <%= @flat.user.firstname %></p>
      <p>Price: <%= @flat.price %>€</p>
      <p>Capicity: <%= @flat.capacity %></p>
      <p>Location: <%= @flat.address %> at <%= @flat.city %></p>
      <% if @flat.rating == nil %>
        <p><span>No reviews</span></p>
      <% else %>
        <p><span class="rating"><% @flat.rating.times do %>☆<% end %></span></p>
      <% end %>
  </div>
  <div class="buttons-flats">
    <% unless current_user == @flat.user %>
      <%= link_to "Book now", new_flat_booking_path(@flat), class: "btn" %>
      <%= link_to "Back to flats", flats_path, class: "green-button" %>
    <% else %>
      <%= link_to "Edit flat", edit_flat_path(@flat), class: "btn" %>
      <%= link_to "Delete", flat_path(@flat), class: "btn", method: :delete, data: { confirm: "Are you sure?" } %>
    <%= link_to "Back to flats", flats_path, class: "green-button" %>
    <% end %>
    </div>
  </div>
</div>
<div class="container-all-reviews">
<h3 class="review-title">Reviews</h3>
<% @flat.reviews.each do |review| %>
<div class="container-review">
    <p class="inbox-review">
        <p class="review">
        <% unless review.user.photo.nil? %>
          <img class="avatar-large" src="<%= review.user.photo.url %>">
        <% else %>
          <img class="avatar-large" src="http://placehold.it/30x30">
        <% end %>
            <div class="message-name">
                <h3><%= review.user.firstname %> <%= review.user.lastname %></h3>
                <p><%= Date.today %></p>
            </div>
             <div class="message-body-review">
            <p>
                <%= review.content %>
            </p>
            </div>
        </li>
    </ul>
    </div>
    <% end %>

<br>
</div>
<%= render 'review-form' %>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>