config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/flats'
  get 'dashboard/bookings'

  resources :flats do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create, :edit, :update] do
      member do
        patch '/accept', to: "bookings#accept"
        patch '/decline', to: "bookings#decline"
      end
    end
  end

  resources :users, only: [:edit, :update]

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner-main" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 10%, rgba(0,36,61,0.3) 70%), url(<%= image_path('santorini.jpg') %>);">
  <div class="banner-content">
    <h1> Book unique homes and experiences all over the world.
    </h1>
    <div class="input-group" id="stylish-input-group">
      <%= form_tag flats_path, class: "form-inline", method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          id: "form-control",
          placeholder: "Try 'Barcelona'" %>

      <span class="input-group-addon">
      </span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="footer">
        <div class="footer-contents">
          <h4>Airbnb</h4>
          <ul class="footer-links">
            <li><a href="#">Careers</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#">Policies</a></li>
            <li><a href="#">Help</a></li>
            <li><a href="#">Diversity & Belonging</a></li>
          </ul>
        </div>

        <div class="footer-contents">
          <h4>Discover</h4>
          <ul class="footer-links">
            <li><a href="#">Trust & Safety</a></li>
            <li><a href="#">Travel Credit</a></li>
            <li><a href="#">Gift Cards</a></li>
            <li><a href="#">Airbnb Citizen</a></li>
            <li><a href="#">Business Travel</a></li>
            <li><a href="#">Guidebooks</a></li>
          </ul>
        </div>

        <div class="footer-contents">
          <h4>Hosting</h4>
          <ul class="footer-links">
            <li><a href="#">Why Host</a></li>
            <li><a href="#">Hospitality</a></li>
            <li><a href="#">Responsible Hosting</a></li>
            <li><a href="#">Community Center</a></li>
          </ul>
        </div>


        <div class="footer-contents">
          <ul class="footer-links">
            <div class="footer-icons">
              <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
              <li><a href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a href="#"><i class="fab fa-instagram"></i></a></li>
            </div>
              <li><a href="#">Terms</a></li>
              <li><a href="#">Privacy</a></li>
              <li><a href="#">Site Map</a></li>
          </ul>
        </div>
    </div>
  </footer>
 

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand justify-start">
    <%= image_tag('logo.png') %>
  </a>

  <% if user_signed_in? %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if policy(Flat).create? %>
      <%= link_to "Add a new flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <%= link_to "Flats", flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "My flats", dashboard_flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "My bookings", dashboard_bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

      <!-- line below commented out and replaced by the two lines below it -->
      <% unless current_user.photo.url.nil? %>
        <img src='<%= cl_image_path current_user.photo %>' class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
      <% else %>
        <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <% end %>


        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Profile", edit_user_path(current_user) %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %></li>
        </ul>
      </div>
    </div>
  </div>

  <% else %>
    <%= link_to "Sign In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>